services:
  frigate-backup:
    build: .
    container_name: frigate-backup
    restart: unless-stopped
    environment:
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - MQTT_TOPIC=frigate/backup/stats
    volumes:
      - ./rclone.conf:/root/.config/rclone/rclone.conf:ro
      - ./synced_events.txt:/app/synced_events.txt
      - ./logs:/root/log_sauvegarde
      - /votre/chemin/media:/root/media:ro